# Generated by Django 5.1.3 on 2024-11-30 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0002_remove_profile_email_remove_profile_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='registration_date',
        ),
    ]
